services:
  - type: web
    name: your-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 app:app  # Make sure to use Gunicorn or another WSGI server
    envVars:
      - key: FLASK_ENV
        value: production
