"""Added foreign key relationships

Revision ID: 5b4470c83efc
Revises: 41a16a5d1d5c
Create Date: 2024-09-18 19:42:33.279929+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4470c83efc'
down_revision = '41a16a5d1d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
#         batch_op.alter_column('quiz_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#         batch_op.drop_constraint('fk_user_question', type_='foreignkey')
#         batch_op.drop_column('user_id')

#     with op.batch_alter_table('quiz', schema=None) as batch_op:
#         batch_op.alter_column('title',
#                existing_type=sa.VARCHAR(length=100),
#                type_=sa.String(length=120),
#                existing_nullable=False)
#         batch_op.alter_column('description',
#                existing_type=sa.VARCHAR(length=255),
#                type_=sa.Text(),
#                existing_nullable=True)
#         batch_op.alter_column('user_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
