"""Add foreign key for questions to quizzes

Revision ID: 60ff0140141a
Revises: 50dbcca372ae
Create Date: 2024-09-13 21:01:06.916229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '60ff0140141a'
down_revision = '50dbcca372ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_question_quiz', 'quiz', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_quiz', type_='foreignkey')
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
