"""fix relationships

Revision ID: 868698021226
Revises: 7e743bed4cd1
Create Date: 2024-09-19 21:42:34.891315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868698021226'
down_revision = '7e743bed4cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('text')
        batch_op.drop_column('is_correct')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
