"""fix relationships

Revision ID: e12fc4b0f684
Revises: 868698021226
Create Date: 2024-09-19 21:58:34.312029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12fc4b0f684'
down_revision = '868698021226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'option', ['option_id'], ['id'])

    # ### end Alembic commands ###
